[package]
name = "sync-test"
version = "0.1.0"
authors = ["Thom Chiovoloni <tchiovoloni@mozilla.com>"]
edition = "2018"
license = "MPL-2.0"

[dependencies]
viaduct-reqwest = { path = "../../components/support/viaduct-reqwest" }
logins = { path = "../../components/logins" }
sync15 = { path = "../../components/sync15" }
sync15-traits = { path = "../../components/support/sync15-traits" }
tabs = { path = "../../components/tabs" }
fxa-client = { path = "../../components/fxa-client" }
sync-guid = { path = "../../components/support/guid", features = ["rusqlite_support", "random"]}
interrupt = { path = "../../components/support/interrupt" }
url = "2.1.1"
env_logger = "0.7.0"
log = "0.4.8"
failure = "0.1.6"
rand = "0.7.2"
lazy_static = "1.4.0"
structopt = "0.3.11"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.50"
